name: Update News
on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install deps
        run: pip install requests beautifulsoup4 pillow lxml
      - name: Run bot
        run: python news.py
      - name: Commit and push
        run: |
          git config --global user.email "bot@4thpillar.com"
          git config --global user.name "News Bot"
          git add news.json images/ .nojekyll -f
          git add images/
          git commit -m "news update 500 bank" || exit 0
          git push
