name: Auto News Update

on:
  schedule:
    - cron: '0 */2 * * *' # Har 2 ghante me auto chalega
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install requests
      - run: python news.py
        env:
          GNEWS_API_KEY: ${{ secrets.GNEWS_API_KEY }}
      - run: |
          git config --global user.name "Gaurav Sharma"
          git config --global user.email "gaurav@4thpillarnews.com"
          git add data/news.json
          git commit -m "Auto news update with rewrite" || echo "No changes"
          git push
