name: build
on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install requests beautifulsoup4 pillow lxml
      - name: Run news script
        run: python news.py
      - name: Commit
        run: |
          git config --global user.name "4thPillarBot"
          git config --global user.email "bot@4thpillarnews.github.io"
          git add news.json
          git commit -m "auto update $(date)" || echo "no change"
          git push
